# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qO9IUfXQtiIsDiriq-1PrC1dFGvmFvPg
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/SampleSuperstore.csv")

ship_mode = df["Ship Mode"].to_numpy()
print(ship_mode)

segment = df["Segment"].to_numpy()
print(segment)

country = df["Country"].to_numpy()
print(country)

city = df["City"].to_numpy()
print(city)

state = df["State"].to_numpy()
print(state)

postal_code = df["Postal Code"].to_numpy()
print(postal_code)

Region = df["Region"].to_numpy()
print(Region)

Category = df["Category"].to_numpy()
print(Category)

Sub_Category = df["Sub-Category"].to_numpy()
print(Sub_Category)

Sales = df["Sales"].to_numpy()
print(Sales)

Quantity = df["Quantity"].to_numpy()
print(Quantity)

Discount = df["Discount"].to_numpy()
print(Discount)

Profit = df["Profit"].to_numpy()
print(Profit)

print("The sales dataset has been loaded, and relevant columns have been converted into NumPy arrays:")
if 'df' in locals():
    numpy_array_names = [
        "ship_mode", "segment", "country", "city", "state", "postal_code",
        "region", "category", "sub_category", "sales", "quantity", "discount", "profit"
    ]

    for name in numpy_array_names:
        if name in locals():
            arr = locals()[name]
            print(f"- '{name}' (shape: {arr.shape}, dtype: {arr.dtype})")
        else:
            print(f"- '{name}' was not found or not yet defined.")
else:
    print("The DataFrame 'df' was not found. Please ensure the dataset is loaded.")

total_sales = np.sum(Sales)
average_sales = np.mean(Sales)

print(f"Total Sales: {total_sales:.2f}")
print(f"Average Sales: {average_sales:.2f}")

# Extract the first 5 sales records
first_five_sales = Sales[:5]
print(f"First 5 sales records: {first_five_sales}")

# Extract sales records from index 10 to 14 (inclusive)
sales_10_to_14 = Sales[10:15]
print(f"Sales records from index 10 to 14: {sales_10_to_14}")

# Extract every 10th sales record
every_tenth_sales = Sales[::1000]
print(f"Every 1000th sales record: {every_tenth_sales}")

# Extract sales records where sales are greater than 500
high_sales_records = Sales[Sales > 500]
print(f"Sales records greater than 500 (first 10 examples): {high_sales_records[:10]}")
print(f"Total count of sales records greater than 500: {len(high_sales_records)}")

mean_sales = np.mean(Sales)
median_sales = np.median(Sales)
variance_sales = np.var(Sales)
std_dev_sales = np.std(Sales)

print(f"Mean Sales: {mean_sales:.2f}")
print(f"Median Sales: {median_sales:.2f}")
print(f"Variance of Sales: {variance_sales:.2f}")
print(f"Standard Deviation of Sales: {std_dev_sales:.2f}")

unit_price_per_item = Sales / Quantity
revenue_per_item = unit_price_per_item * Quantity

print(f"First 5 calculated Unit Prices per item: {unit_price_per_item[:5]}")
print(f"First 5 calculated Revenues per item (should be same as sales): {revenue_per_item[:5]}")

print(f"\nAre calculated revenues equal to the original sales array? {np.allclose(revenue_per_item, Sales)}")

profit_margin = (Profit /Sales) * 100

print(f"First 10 calculated Profit Margins: {profit_margin[:10].round(2)}%")
print(f"Average Profit Margin across all sales: {np.mean(profit_margin).round(2)}%")

# Find sales where profit margin is negative (indicating a loss)
loss_making_sales_count = np.sum(profit_margin < 0)
print(f"Number of sales with a negative profit margin (loss): {loss_making_sales_count}")